title: Pablo NIETO # your name (or website title) here
logo: "/images/photoPabloNieto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of consulting experience with extensive international background
  <br><br>
  Master's degree in Aerospace Engineering from ISAE-SUPAERO and Master's and Bachelor's degree in Industrial Engineering from ETSI-US 
  <br><br>
  <a href="https://www.linkedin.com/in/pablo-nieto-martin">View My LinkedIn Profile</a> 
 
  
theme: jekyll-theme-minimal
